In [2]:
from bs4 import BeautifulSoup
import requests

In [4]:
# 실습 1. 네이버 주가 크롤링

res = requests.get("https://finance.naver.com/sise/sise_quant.nhn")
soup = BeautifulSoup(res.text, 'html.parser')

In [ ]:
soup.select('tr')[0]

<tr>
<td class="choice"><input checked="" id="option1" name="fieldIds" type="checkbox" value="quant"/> <label for="option1">거래량</label></td>
<td class="choice"><input checked="" id="option2" name="fieldIds" type="checkbox" value="ask_buy"/> <label for="option2">매수호가</label></td>
<td class="choice"><input checked="" id="option3" name="fieldIds" type="checkbox" value="amount"/> <label for="option3">거래대금</label>(백만)</td>
<td class="choice"><input checked="" id="option4" name="fieldIds" type="checkbox" value="market_sum"/> <label for="option4">시가총액</label>(억)</td>
<td><input id="option5" name="fieldIds" type="checkbox" value="operating_profit"/> <label for="option5">영업이익</label>(억)</td>
<td class="choice"><input checked="" id="option6" name="fieldIds" type="checkbox" value="per"/> <label for="option6">PER</label>(배)</td>
</tr>

In [28]:
soup.select('td')

[<td class="choice"><input checked="" id="option1" name="fieldIds" type="checkbox" value="quant"/> <label for="option1">거래량</label></td>,
 <td class="choice"><input checked="" id="option2" name="fieldIds" type="checkbox" value="ask_buy"/> <label for="option2">매수호가</label></td>,
 <td class="choice"><input checked="" id="option3" name="fieldIds" type="checkbox" value="amount"/> <label for="option3">거래대금</label>(백만)</td>,
 <td class="choice"><input checked="" id="option4" name="fieldIds" type="checkbox" value="market_sum"/> <label for="option4">시가총액</label>(억)</td>,
 <td><input id="option5" name="fieldIds" type="checkbox" value="operating_profit"/> <label for="option5">영업이익</label>(억)</td>,
 <td class="choice"><input checked="" id="option6" name="fieldIds" type="checkbox" value="per"/> <label for="option6">PER</label>(배)</td>,
 <td><input id="option7" name="fieldIds" type="checkbox" value="open_val"/> <label for="option7">시가</label></td>,
 <td class="choice"><input checked="" id="option8" name="fieldIds" type="checkbox" value="ask_sell"/> <label for="option8">매도호가</label></td>,
 <td><input id="option9" name="fieldIds" type="checkbox" value="prev_quant"/> <label for="option9">전일거래량</label></td>,
 <td><input id="option10" name="fieldIds" type="checkbox" value="property_total"/> <label for="option10">자산총계</label>(억)</td>,
 <td><input id="option11" name="fieldIds" type="checkbox" value="operating_profit_increasing_rate"/> <label for="option11">영업이익증가율</label></td>,
 <td class="choice"><input checked="" id="option12" name="fieldIds" type="checkbox" value="roe"/> <label for="option12">ROE</label>(%)</td>,
 <td><input id="option13" name="fieldIds" type="checkbox" value="high_val"/> <label for="option13">고가</label></td>,
 <td><input id="option14" name="fieldIds" type="checkbox" value="buy_total"/> <label for="option14">매수총잔량</label></td>,
 <td><input id="option15" name="fieldIds" type="checkbox" value="frgn_rate"/> <label for="option15">외국인비율</label></td>,
 <td><input id="option16" name="fieldIds" type="checkbox" value="debt_total"/> <label for="option16">부채총계</label>(억)</td>,
 <td><input id="option17" name="fieldIds" type="checkbox" value="net_income"/> <label for="option17">당기순이익</label>(억)</td>,
 <td><input id="option18" name="fieldIds" type="checkbox" value="roa"/> <label for="option18">ROA</label>(%)</td>,
 <td><input id="option19" name="fieldIds" type="checkbox" value="low_val"/> <label for="option19">저가</label></td>,
 <td><input id="option20" name="fieldIds" type="checkbox" value="sell_total"/> <label for="option20">매도총잔량</label></td>,
 <td><input id="option21" name="fieldIds" type="checkbox" value="listed_stock_cnt"/> <label for="option21">상장주식수</label>(천주)</td>,
 <td><input id="option22" name="fieldIds" type="checkbox" value="sales"/> <label for="option22">매출액</label>(억)</td>,
 <td><input id="option23" name="fieldIds" type="checkbox" value="eps"/> <label for="option23">주당순이익</label>(원)</td>,
 <td><input id="option24" name="fieldIds" type="checkbox" value="pbr"/> <label for="option24">PBR</label>(배)</td>,
 <td> </td>,
 <td> </td>,
 <td> </td>,
 <td><input id="option25" name="fieldIds" type="checkbox" value="sales_increasing_rate"/> <label for="option25">매출액증가율</label></td>,
 <td><input id="option26" name="fieldIds" type="checkbox" value="dividend"/> <label for="option26">보통주배당금</label>(원)</td>,
 <td><input id="option27" name="fieldIds" type="checkbox" value="reserve_ratio"/> <label for="option27">유보율</label>(%)</td>,
 <td class="blank_08" colspan="10"></td>,
 <td class="no">1</td>,
 <td><a class="tltle" href="/item/main.naver?code=252670">KODEX 200선물인버스2X</a></td>,
 <td class="number">1,380</td>,
 <td class="number">
 <em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
 				45
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-3.16%
 				</span>
 </td>,
 <td class="number">362,141,880</td>,
 <td class="number">504,465</td>,
 <td class="number">1,380</td>,
 <td class="number">1,381</td>,
 <td class="number">13,863</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">2</td>,
 <td><a class="tltle" href="/item/main.naver?code=462330">KODEX 2차전지산업레버리지</a></td>,
 <td class="number">990</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				96
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+10.74%
 				</span>
 </td>,
 <td class="number">49,582,923</td>,
 <td class="number">47,717</td>,
 <td class="number">988</td>,
 <td class="number">990</td>,
 <td class="number">2,711</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">3</td>,
 <td><a class="tltle" href="/item/main.naver?code=008970">동양철관</a></td>,
 <td class="number">1,532</td>,
 <td class="number">
 <em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
 				112
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-6.81%
 				</span>
 </td>,
 <td class="number">45,589,364</td>,
 <td class="number">73,920</td>,
 <td class="number">1,531</td>,
 <td class="number">1,532</td>,
 <td class="number">2,448</td>,
 <td class="number">-10.57</td>,
 <td class="number">-20.13</td>,
 <td class="no">4</td>,
 <td><a class="tltle" href="/item/main.naver?code=005320">온타이드</a></td>,
 <td class="number">674</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				11
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.66%
 				</span>
 </td>,
 <td class="number">35,169,753</td>,
 <td class="number">27,445</td>,
 <td class="number">673</td>,
 <td class="number">674</td>,
 <td class="number">455</td>,
 <td class="number">56.17</td>,
 <td class="number">-3.35</td>,
 <td class="no">5</td>,
 <td><a class="tltle" href="/item/main.naver?code=005930">삼성전자</a></td>,
 <td class="number">63,800</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				3,000
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+4.93%
 				</span>
 </td>,
 <td class="number">31,792,165</td>,
 <td class="number">1,990,967</td>,
 <td class="number">63,700</td>,
 <td class="number">63,800</td>,
 <td class="number">3,776,729</td>,
 <td class="number">12.36</td>,
 <td class="number">9.03</td>,
 <td class="blank_06" colspan="12"></td>,
 <td class="division_line" colspan="12"></td>,
 <td class="blank_08" colspan="12"></td>,
 <td class="no">6</td>,
 <td><a class="tltle" href="/item/main.naver?code=114800">KODEX 인버스</a></td>,
 <td class="number">3,570</td>,
 <td class="number">
 <em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
 				65
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-1.79%
 				</span>
 </td>,
 <td class="number">30,908,865</td>,
 <td class="number">110,943</td>,
 <td class="number">3,570</td>,
 <td class="number">3,575</td>,
 <td class="number">6,508</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">7</td>,
 <td><a class="tltle" href="/item/main.naver?code=233740">KODEX 코스닥150레버리지</a></td>,
 <td class="number">8,335</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				275
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+3.41%
 				</span>
 </td>,
 <td class="number">28,292,829</td>,
 <td class="number">232,868</td>,
 <td class="number">8,335</td>,
 <td class="number">8,340</td>,
 <td class="number">19,746</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">8</td>,
 <td><a class="tltle" href="/item/main.naver?code=122630">KODEX 레버리지</a></td>,
 <td class="number">23,835</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				715
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+3.09%
 				</span>
 </td>,
 <td class="number">25,755,037</td>,
 <td class="number">608,284</td>,
 <td class="number">23,830</td>,
 <td class="number">23,835</td>,
 <td class="number">25,444</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">9</td>,
 <td><a class="tltle" href="/item/main.naver?code=009070">KCTC</a></td>,
 <td class="number">6,250</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				770
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+14.05%
 				</span>
 </td>,
 <td class="number">24,282,307</td>,
 <td class="number">152,088</td>,
 <td class="number">6,250</td>,
 <td class="number">6,260</td>,
 <td class="number">1,875</td>,
 <td class="number">8.94</td>,
 <td class="number">9.06</td>,
 <td class="no">10</td>,
 <td><a class="tltle" href="/item/main.naver?code=251340">KODEX 코스닥150선물인버스</a></td>,
 <td class="number">3,570</td>,
 <td class="number">
 <em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
 				60
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-1.65%
 				</span>
 </td>,
 <td class="number">21,214,805</td>,
 <td class="number">76,286</td>,
 <td class="number">3,570</td>,
 <td class="number">3,575</td>,
 <td class="number">2,135</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="blank_06" colspan="12"></td>,
 <td class="division_line" colspan="12"></td>,
 <td class="blank_08" colspan="12"></td>,
 <td class="no">11</td>,
 <td><a class="tltle" href="/item/main.naver?code=530036">삼성 인버스 2X WTI원유 선물 ETN</a></td>,
 <td class="number">77</td>,
 <td class="number">
 <em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
 				3
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-3.75%
 				</span>
 </td>,
 <td class="number">20,209,689</td>,
 <td class="number">1,555</td>,
 <td class="number">77</td>,
 <td class="number">78</td>,
 <td class="number">1,153</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">12</td>,
 <td><a class="tltle" href="/item/main.naver?code=450140">코오롱모빌리티그룹</a></td>,
 <td class="number">2,630</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				195
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+8.01%
 				</span>
 </td>,
 <td class="number">18,337,732</td>,
 <td class="number">50,756</td>,
 <td class="number">2,625</td>,
 <td class="number">2,630</td>,
 <td class="number">1,651</td>,
 <td class="number">-38.12</td>,
 <td class="number">-5.62</td>,
 <td class="no">13</td>,
 <td><a class="tltle" href="/item/main.naver?code=500027">신한 인버스 2X WTI원유 선물 ETN(H)</a></td>,
 <td class="number">66</td>,
 <td class="number">
 <em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
 				3
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-4.35%
 				</span>
 </td>,
 <td class="number">16,439,215</td>,
 <td class="number">1,070</td>,
 <td class="number">65</td>,
 <td class="number">66</td>,
 <td class="number">418</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">14</td>,
 <td><a class="tltle" href="/item/main.naver?code=004140">동방</a></td>,
 <td class="number">2,990</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				110
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+3.82%
 				</span>
 </td>,
 <td class="number">15,097,937</td>,
 <td class="number">45,907</td>,
 <td class="number">2,985</td>,
 <td class="number">2,990</td>,
 <td class="number">1,434</td>,
 <td class="number">8.90</td>,
 <td class="number">13.73</td>,
 <td class="no">15</td>,
 <td><a class="tltle" href="/item/main.naver?code=002630">오리엔트바이오</a></td>,
 <td class="number">807</td>,
 <td class="number">
 <em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
 				17
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-2.06%
 				</span>
 </td>,
 <td class="number">12,992,658</td>,
 <td class="number">10,868</td>,
 <td class="number">807</td>,
 <td class="number">809</td>,
 <td class="number">957</td>,
 <td class="number">-7.27</td>,
 <td class="number">-16.82</td>,
 <td class="blank_06" colspan="12"></td>,
 <td class="division_line" colspan="12"></td>,
 <td class="blank_08" colspan="12"></td>,
 <td class="no">16</td>,
 <td><a class="tltle" href="/item/main.naver?code=093240">형지엘리트</a></td>,
 <td class="number">3,175</td>,
 <td class="number">
 <em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
 				5
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.16%
 				</span>
 </td>,
 <td class="number">11,248,931</td>,
 <td class="number">35,834</td>,
 <td class="number">3,170</td>,
 <td class="number">3,175</td>,
 <td class="number">1,219</td>,
 <td class="number">39.20</td>,
 <td class="number">8.75</td>,
 <td class="no">17</td>,
 <td><a class="tltle" href="/item/main.naver?code=412570">TIGER 2차전지TOP10레버리지</a></td>,
 <td class="number">1,125</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				115
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+11.39%
 				</span>
 </td>,
 <td class="number">9,531,155</td>,
 <td class="number">10,493</td>,
 <td class="number">1,124</td>,
 <td class="number">1,125</td>,
 <td class="number">924</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">18</td>,
 <td><a class="tltle" href="/item/main.naver?code=069500">KODEX 200</a></td>,
 <td class="number">42,305</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				645
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+1.55%
 				</span>
 </td>,
 <td class="number">8,849,304</td>,
 <td class="number">372,929</td>,
 <td class="number">42,305</td>,
 <td class="number">42,310</td>,
 <td class="number">66,525</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">19</td>,
 <td><a class="tltle" href="/item/main.naver?code=003280">흥아해운</a></td>,
 <td class="number">1,813</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				11
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.61%
 				</span>
 </td>,
 <td class="number">8,797,261</td>,
 <td class="number">15,920</td>,
 <td class="number">1,813</td>,
 <td class="number">1,814</td>,
 <td class="number">4,359</td>,
 <td class="number">11.40</td>,
 <td class="number">20.08</td>,
 <td class="no">20</td>,
 <td><a class="tltle" href="/item/main.naver?code=009830">한화솔루션</a></td>,
 <td class="number">36,300</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				850
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+2.40%
 				</span>
 </td>,
 <td class="number">8,239,831</td>,
 <td class="number">296,615</td>,
 <td class="number">36,300</td>,
 <td class="number">36,350</td>,
 <td class="number">62,397</td>,
 <td class="number">-6.40</td>,
 <td class="number">-15.99</td>,
 <td class="blank_06" colspan="12"></td>,
 <td class="division_line" colspan="12"></td>,
 <td class="blank_08" colspan="12"></td>,
 <td class="no">21</td>,
 <td><a class="tltle" href="/item/main.naver?code=462010">TIGER 2차전지소재Fn</a></td>,
 <td class="number">3,815</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				175
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+4.81%
 				</span>
 </td>,
 <td class="number">7,736,175</td>,
 <td class="number">29,287</td>,
 <td class="number">3,815</td>,
 <td class="number">3,820</td>,
 <td class="number">4,757</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">22</td>,
 <td><a class="tltle" href="/item/main.naver?code=305720">KODEX 2차전지산업</a></td>,
 <td class="number">11,475</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				555
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+5.08%
 				</span>
 </td>,
 <td class="number">7,246,353</td>,
 <td class="number">82,335</td>,
 <td class="number">11,470</td>,
 <td class="number">11,475</td>,
 <td class="number">10,029</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">23</td>,
 <td><a class="tltle" href="/item/main.naver?code=034020">두산에너빌리티</a></td>,
 <td class="number">61,900</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				300
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.49%
 				</span>
 </td>,
 <td class="number">6,984,206</td>,
 <td class="number">436,251</td>,
 <td class="number">61,800</td>,
 <td class="number">61,900</td>,
 <td class="number">396,507</td>,
 <td class="number">-389.31</td>,
 <td class="number">1.52</td>,
 <td class="no">24</td>,
 <td><a class="tltle" href="/item/main.naver?code=364980">TIGER 2차전지TOP10</a></td>,
 <td class="number">8,055</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				420
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+5.50%
 				</span>
 </td>,
 <td class="number">6,826,713</td>,
 <td class="number">54,106</td>,
 <td class="number">8,040</td>,
 <td class="number">8,055</td>,
 <td class="number">3,774</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">25</td>,
 <td><a class="tltle" href="/item/main.naver?code=002700">신일전자</a></td>,
 <td class="number">1,621</td>,
 <td class="number">
 <em class="bu_p bu_pup"><span class="blind">상승</span></em><span class="tah p11 red02">
 				4
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 red01">
 				+0.25%
 				</span>
 </td>,
 <td class="number">6,289,419</td>,
 <td class="number">10,041</td>,
 <td class="number">1,620</td>,
 <td class="number">1,621</td>,
 <td class="number">1,152</td>,
 <td class="number">67.54</td>,
 <td class="number">1.76</td>,
 <td class="blank_06" colspan="12"></td>,
 <td class="division_line" colspan="12"></td>,
 <td class="blank_08" colspan="12"></td>,
 <td class="no">26</td>,
 <td><a class="tltle" href="/item/main.naver?code=228790">TIGER 화장품</a></td>,
 <td class="number">4,025</td>,
 <td class="number">
 <em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
 				15
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-0.37%
 				</span>
 </td>,
 <td class="number">5,883,159</td>,
 <td class="number">23,673</td>,
 <td class="number">4,020</td>,
 <td class="number">4,025</td>,
 <td class="number">2,614</td>,
 <td class="number">N/A</td>,
 <td class="number">N/A</td>,
 <td class="no">27</td>,
 <td><a class="tltle" href="/item/main.naver?code=005690">파미셀</a></td>,
 <td class="number">11,580</td>,
 <td class="number">
 <em class="bu_p bu_pdn"><span class="blind">하락</span></em><span class="tah p11 nv01">
 				650
 				</span>
 </td>,
 <td class="number">
 <span class="tah p11 nv01">
 				-5.31%
 				</span>
 </td>,
 <td class="number">5,796,403</td>,
 <td class="number">71,106</td>,
 <td class="number">11,570</td>,
 <td class="number">11,580</td>,
 <td class="number">6,950</td>,
 <td class="number">43.05</td>,
 <td class="number">7.59</td>,
 <td class="no">28</td>,

In [37]:
table = soup.select_one('table.type_2')
rows = table.select('tr')[2:]

In [38]:
result = []

for row in rows:
    columns = row.select('td')
    if len(columns) > 1:
        name = columns[1].text.strip()
        price = columns[2].text.strip()
        result.append({'name': name, 'price': price})

print(result)

[{'name': 'KODEX 200선물인버스2X', 'price': '1,380'}, {'name': 'KODEX 2차전지산업레버리지', 'price': '990'}, {'name': '동양철관', 'price': '1,532'}, {'name': '온타이드', 'price': '674'}, {'name': '삼성전자', 'price': '63,800'}, {'name': 'KODEX 인버스', 'price': '3,570'}, {'name': 'KODEX 코스닥150레버리지', 'price': '8,335'}, {'name': 'KODEX 레버리지', 'price': '23,835'}, {'name': 'KCTC', 'price': '6,250'}, {'name': 'KODEX 코스닥150선물인버스', 'price': '3,570'}, {'name': '삼성 인버스 2X WTI원유 선물 ETN', 'price': '77'}, {'name': '코오롱모빌리티그룹', 'price': '2,630'}, {'name': '신한 인버스 2X WTI원유 선물 ETN(H)', 'price': '66'}, {'name': '동방', 'price': '2,990'}, {'name': '오리엔트바이오', 'price': '807'}, {'name': '형지엘리트', 'price': '3,175'}, {'name': 'TIGER 2차전지TOP10레버리지', 'price': '1,125'}, {'name': 'KODEX 200', 'price': '42,305'}, {'name': '흥아해운', 'price': '1,813'}, {'name': '한화솔루션', 'price': '36,300'}, {'name': 'TIGER 2차전지소재Fn', 'price': '3,815'}, {'name': 'KODEX 2차전지산업', 'price': '11,475'}, {'name': '두산에너빌리티', 'price': '61,900'}, {'name': 'TIGER 2차전지TOP10', 'price': '8,055'}, {'name': '신일전자', 'price': '1,621'}, {'name': 'TIGER 화장품', 'price': '4,025'}, {'name': '파미셀', 'price': '11,580'}, {'name': 'SK증권', 'price': '687'}, {'name': 'KODEX 코스닥150', 'price': '12,905'}, {'name': '현대제철', 'price': '35,550'}, {'name': 'ACE 테슬라밸류체인액티브', 'price': '14,535'}, {'name': 'RISE 테슬라고정테크100', 'price': '10,950'}, {'name': '한국전력', 'price': '35,900'}, {'name': '대한해운', 'price': '1,710'}, {'name': 'TIGER 200선물인버스2X', 'price': '1,461'}, {'name': '삼성중공업', 'price': '16,290'}, {'name': '서울식품', 'price': '169'}, {'name': 'KODEX AI전력핵심설비', 'price': '14,625'}, {'name': '한일철강', 'price': '2,965'}, {'name': '대영포장', 'price': '1,241'}, {'name': '신원', 'price': '1,806'}, {'name': 'KODEX 2차전지핵심소재10', 'price': '3,900'}, {'name': '삼성 인버스 2X 코스닥150 선물 ETN', 'price': '5,420'}, {'name': '신성이엔지', 'price': '1,544'}, {'name': 'SK하이닉스', 'price': '278,500'}, {'name': 'TIGER 미국S&P500', 'price': '21,075'}, {'name': 'HD현대인프라코어', 'price': '12,040'}, {'name': '카카오', 'price': '59,500'}, {'name': 'N2 인버스 레버리지 WTI원유 선물 ETN(H)', 'price': '60'}, {'name': '인디에프', 'price': '1,415'}, {'name': '한화투자증권', 'price': '6,510'}, {'name': 'KODEX 200타겟위클리커버드콜', 'price': '11,180'}, {'name': '미래에셋증권', 'price': '21,550'}, {'name': 'TIGER 인터넷TOP10', 'price': '4,755'}, {'name': '이수페타시스', 'price': '52,500'}, {'name': '삼성 레버리지 WTI원유 선물 ETN', 'price': '1,283'}, {'name': '한국특강', 'price': '1,523'}, {'name': 'LG디스플레이', 'price': '9,520'}, {'name': 'KODEX 증권', 'price': '13,780'}, {'name': '현대로템', 'price': '196,100'}, {'name': 'ACE 미국30년국채액티브(H)', 'price': '7,790'}, {'name': '삼성전자우', 'price': '52,900'}, {'name': '카카오페이', 'price': '77,000'}, {'name': 'TIGER 200', 'price': '42,265'}, {'name': 'KODEX 미국S&P500', 'price': '19,395'}, {'name': 'SOL 조선TOP3플러스', 'price': '24,520'}, {'name': '대한항공', 'price': '24,000'}, {'name': 'TIGER 차이나항셍테크', 'price': '7,850'}, {'name': '인스코비', 'price': '1,469'}, {'name': '엑시큐어하이트론', 'price': '635'}, {'name': 'PLUS 고배당주', 'price': '19,400'}, {'name': 'TIGER 미국테크TOP10 INDXX', 'price': '24,290'}, {'name': 'YG PLUS', 'price': '8,220'}, {'name': '에코프로머티', 'price': '53,800'}, {'name': '대한전선', 'price': '16,010'}, {'name': 'HMM', 'price': '23,900'}, {'name': '일신석재', 'price': '2,410'}, {'name': 'TIGER Fn반도체TOP10', 'price': '11,945'}, {'name': '파라다이스', 'price': '15,560'}, {'name': 'TIGER 2차전지테마', 'price': '14,450'}, {'name': '이스타코', 'price': '785'}, {'name': '애경케미칼', 'price': '12,060'}, {'name': 'TIGER 바이오TOP10', 'price': '7,670'}, {'name': '유진투자증권', 'price': '3,585'}, {'name': '한화생명', 'price': '3,300'}, {'name': '팬오션', 'price': '3,890'}, {'name': 'TIGER 조선TOP10', 'price': '19,245'}, {'name': '평화산업', 'price': '1,090'}, {'name': 'TIGER 미국30년국채커버드콜액티브(H)', 'price': '8,060'}, {'name': '한국ANKOR유전', 'price': '253'}, {'name': 'TIGER 200 중공업', 'price': '10,425'}, {'name': 'TIGER 소프트웨어', 'price': '10,010'}, {'name': 'KODEX AI반도체핵심장비', 'price': '10,245'}, {'name': 'TIGER 코리아배당다우존스', 'price': '11,950'}, {'name': '삼성 레버리지 천연가스 선물 ETN C', 'price': '3,920'}, {'name': 'KODEX 바이오', 'price': '9,295'}, {'name': '일진전기', 'price': '37,200'}, {'name': '대한제당', 'price': '3,120'}, {'name': '이구산업', 'price': '5,210'}, {'name': 'KODEX 반도체레버리지', 'price': '11,800'}]